version: '3'
services:
  web:
    image: blog-post-api
    build: .
    command: "node api.js"
    ports:
      - "9000:8080"
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
    ports:
      - '27017:27017'      
